include ../Make.defines
PROGRAM = tcpserver_poll
OBJS = tcpserver_poll.o
PROGS = tcpserver_poll


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
