include ../Make.defines
PROGRAM = daytimetcpserver
OBJS = daytimetcpserver.o
PROGS = daytimetcpserver


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
