include ../../Make.definesfortraceroute
PROGRAM = udpcli
OBJS = udpcli.o dg_cli.o
PROGS = udpcli


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
