include ../Make.defines
PROGRAM = udpclimulticast
OBJS = udpclimulticast.o
PROGS = udpclimulticast


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
