include ../Make.defines
PROGRAM = udpclibrdcst4
OBJS = udpclibrdcst4.o
PROGS = udpclibrdcst4


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
