include ../Make.defines
PROGRAM = tcpserver_thread1
OBJS = tcpserver_thread1.o
PROGS = tcpserver_thread1


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
