include ../Make.defines
PROGRAM = daytimetcpserver1
OBJS = daytimetcpserver1.o
PROGS = daytimetcpserver1


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
