include ../Make.defines
PROGRAM = tcpserver03
OBJS = tcpserver03.o sigchldwaitpid.o
PROGS = tcpserver03


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
