include ../Make.defines
PROGRAM = udpserv
OBJS = dgecho.o recvfromflags.o udpserv.o
PROGS = udpserv


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
