include ../Make.defines
PROGRAM = udpserv_bindall
OBJS = udpserv_bindall.o
PROGS = udpserv_bindall


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
