include ../Make.defines
PROGRAM = unixstrserv01
OBJS = unixstrserv01.o
PROGS = unixstrserv01


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
