include ../Make.defines
PROGRAM = daytimetcpdaemon
OBJS = daytimetcpdeamon.o
PROGS = daytimetcpdaemon


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
