include ../Make.defines
PROGRAM = daytimetcpcli
OBJS = daytimetcpcli.o
PROGS = daytimetcpcli


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
