include ../Make.defines
PROGRAM = daytimetcpserver2
OBJS = daytimetcpserver2.o
PROGS = daytimetcpserver2


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
