include ../Make.defines
PROGRAM = daytimetcpcli2
OBJS = daytimetcpcli2.o
PROGS = daytimetcpcli2


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
