include ../Make.defines
PROGRAM = myaddress
OBJS = myaddress.o my_addr2.o
PROGS = myaddress


all: ${PROGS} 

$(PROGRAM):$(OBJS)
	${CC} ${CFLAGS} -o $@ ${OBJS} ${LIBS}


clean:
	rm -f ${PROGS} ${CLEANFILES}
